### ISSUE TITLE
QuakeFaultHandler testcase is broken

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/FlightSoftware#514]
Still investigating. Failure log:

```
Creating a comms blackout of 24 hours (measured from control cycle #1.) Current control cycle: 6
QuakeFaultHandler forced spacecraft into the standby state.
Creating another comms blackout of 24 hours, starting on control cycle 60
Comms blackout forced a transition into Quake Fault Handler's powercycling states.
Traceback (most recent call last):
  File "/Users/tanishqaggarwal/Documents/pan/repositories/FlightSoftware/ptest/cases/base.py", line 125, in run_case
    self._run_case()
  File "/Users/tanishqaggarwal/Documents/pan/repositories/FlightSoftware/ptest/cases/base.py", line 209, in _run_case
    self.run_case_singlesat()
  File "/Users/tanishqaggarwal/Documents/pan/repositories/FlightSoftware/ptest/cases/quake_fault_handler.py", line 70, in run_case_singlesat
    self.check_quake_powercycled()
  File "/Users/tanishqaggarwal/Documents/pan/repositories/FlightSoftware/ptest/cases/quake_fault_handler.py", line 26, in check_quake_powercycled
    raise self.TestCaseFailure("Quake radio was not powercycled.")
ptest.cases.base.PTestCase.TestCaseFailure: Quake radio was not powercycled.
```

**Comment by tanishqaggarwal** [comment]
This ticket is duplicated by #509 because the testing there for Quake powercycling will end up including all of the functionality in the QuakeFaultHandler, which will then be deleted.
