### ISSUE TITLE
USB Session Exceptions

### ISSUE THREAD

**Issue by kylekrol** [pathfinder-for-autonomous-navigation/FlightSoftware#557]
After running some long duration HITLs on the flight units, I've hit the following stack trace somewhat frequently after cases have been running for about fifteen minutes or so:

```
Traceback (most recent call last):
  File "/home/kkrol/git/pan/FlightSoftware/ptest/usb_session.py", line 111, in check_console_msgs
    if self.console.inWaiting() > 0:
  File "/home/kkrol/git/pan/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialutil.py", line 590, in inWaiting
    return self.in_waiting
  File "/home/kkrol/git/pan/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error
Unspecified error. Exiting.
 - Terminating console connection to and saving logging/telemetry data for FlightController.
Exception in thread FlightController logger thread:
Traceback (most recent call last):
  File "/home/kkrol/git/pan/FlightSoftware/ptest/usb_session.py", line 111, in check_console_msgs
    if self.console.inWaiting() > 0:
  File "/home/kkrol/git/pan/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialutil.py", line 590, in inWaiting
    return self.in_waiting
  File "/home/kkrol/git/pan/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kkrol/git/pan/FlightSoftware/ptest/usb_session.py", line 169, in check_console_msgs
    self.disconnect()
  File "/home/kkrol/git/pan/FlightSoftware/ptest/usb_session.py", line 447, in disconnect
    self.check_msgs_thread.join()
  File "/usr/lib/python3.8/threading.py", line 1008, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

This has happened while running the `DitlCase` which is very similiar to the `SpinMotorsCase` except it continues to log telemetry over the course of the simulation.

Unfortunately, the ptest logs weren't saved except for the raw log which is attached here:
[FlightController_raw-log.txt](https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/files/5587196/FlightController_raw-log.txt)

**Comment by kylekrol** [comment]
This may be unrelated, but this synchronization in `USBSession` isn't correct:

https://github.com/pathfinder-for-autonomous-navigation/FlightSoftware/blob/a0078703eb03bf9aef6e5ffaf8f27ff56ec188b2/ptest/usb_session.py#L204-L214

The `Queue` doesn't guarantee the threads retrieve things in the order they started blocking.
