### ISSUE TITLE
Bootcount is overwritten by EEPROM

### ISSUE THREAD

**Issue by shihaocao** [pathfinder-for-autonomous-navigation/FlightSoftware#813]
Two things to fix:
Lets loosen the restriction on MissionManager

Second lets change the computation of bootcount and its interaction with EEPROM so the statefield is still meaningful

**Comment by shihaocao** [comment]
Post PR Verification:
(venv) shihao@shihao-T490V2:~/Code/PAN/FlightSoftware$ python -m ptest runsim -c ptest/configs/hitl.json -t EmptyCase
 _______     _       ____  _____                                
|_   __ \   / \     |_   \|_   _|                            
  | |__) | / _ \      |   \ | |                               
  |  ___/ / ___ \     | |\ \| |                              
 _| |_  _/ /   \ \_  _| |_\   |_                             
|_____||____| |____||_____|\____|                              
                                                                
Pathfinder for Autonomous Navigation                            
Space Systems Design Studio, Cornell University       
Console Software | Version 1.0

Opened connection to FlightController.
Running mission testcase EmptyCase.
[TESTCASE] Starting testcase.
[TESTCASE] Suppressing faults.
Turning off fault_handler
Turning off piksi_fh
Turning off qfh
Supressing gomspace.low_batt
Supressing gomspace.get_hk.base
Supressing prop.overpressured
Supressing prop.tank2_temp_high
Supressing prop.tank1_temp_high
Supressing adcs_monitor.functional_fault
Supressing adcs_monitor.wheel1_fault
Supressing adcs_monitor.wheel2_fault
Supressing adcs_monitor.wheel3_fault
Supressing adcs_monitor.wheel_pot_fault
Supressing attitude_estimator.fault
Supressing piksi_fh.dead
[TESTCASE] Auto-dbtelem INACTIVE
[TESTCASE] Scrape-uplink ACTIVE
[TESTCASE] Boot utility waiting to reach initial state.
Beginning console.
Type "help" for a list of commands.
NOTE: You are currently connected to the FlightController.
> [TESTCASE] Finished testcase.

> rs pan.bootcount
1                                               (Completed in 5596 us)
> exit
Exiting command line.
Stopping binary monitor thread...
Stopping uplink console...
Terminating 0 radio connection(s)...
Terminating 1 device connection(s)...
 - Terminating console connection to and saving logging/telemetry data for FlightController.
 - Finished terminating for FlightController.
(venv) shihao@shihao-T490V2:~/Code/PAN/FlightSoftware$ python -m ptest runsim -c ptest/configs/hitl.json -t Reboot
 _______     _       ____  _____                                
|_   __ \   / \     |_   \|_   _|                            
  | |__) | / _ \      |   \ | |                               
  |  ___/ / ___ \     | |\ \| |                              
 _| |_  _/ /   \ \_  _| |_\   |_                             
|_____||____| |____||_____|\____|                              
                                                                
Pathfinder for Autonomous Navigation                            
Space Systems Design Studio, Cornell University       
Console Software | Version 1.0

Opened connection to FlightController.
Running mission testcase Reboot.
[TESTCASE] Starting testcase.
[TESTCASE] Suppressing faults.
Turning off fault_handler
Turning off piksi_fh
Turning off qfh
Supressing gomspace.low_batt
Supressing gomspace.get_hk.base
Supressing prop.overpressured
Supressing prop.tank2_temp_high
Supressing prop.tank1_temp_high
Supressing adcs_monitor.functional_fault
Supressing adcs_monitor.wheel1_fault
Supressing adcs_monitor.wheel2_fault
Supressing adcs_monitor.wheel3_fault
Supressing adcs_monitor.wheel_pot_fault
Supressing attitude_estimator.fault
Supressing piksi_fh.dead
[TESTCASE] Auto-dbtelem INACTIVE
[TESTCASE] Scrape-uplink ACTIVE
[TESTCASE] Boot utility waiting to reach initial state.
Beginning console.
Type "help" for a list of commands.
NOTE: You are currently connected to the FlightController.
> [TESTCASE] Finished testcase.
Traceback (most recent call last):
  File "/home/shihao/Code/PAN/FlightSoftware/ptest/usb_session.py", line 162, in check_console_msgs
    if self.console.inWaiting() > 0:
  File "/home/shihao/Code/PAN/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialutil.py", line 590, in inWaiting
    return self.in_waiting
  File "/home/shihao/Code/PAN/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error
Unspecified error. Exiting.
 - Terminating console connection to and saving logging/telemetry data for FlightController.
Exception in thread FlightController logger thread:
Traceback (most recent call last):
  File "/home/shihao/Code/PAN/FlightSoftware/ptest/usb_session.py", line 162, in check_console_msgs
    if self.console.inWaiting() > 0:
  File "/home/shihao/Code/PAN/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialutil.py", line 590, in inWaiting
    return self.in_waiting
  File "/home/shihao/Code/PAN/FlightSoftware/venv/lib/python3.8/site-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/shihao/Code/PAN/FlightSoftware/ptest/usb_session.py", line 225, in check_console_msgs
    self.disconnect()
  File "/home/shihao/Code/PAN/FlightSoftware/ptest/usb_session.py", line 548, in disconnect
    self.check_msgs_thread.join()
  File "/usr/lib/python3.8/threading.py", line 1008, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

> Exiting command line.
Stopping binary monitor thread...
Stopping uplink console...
Terminating 0 radio connection(s)...
Terminating 1 device connection(s)...
 - Terminating console connection to and saving logging/telemetry data for FlightController.
 - Finished terminating for FlightController.
(venv) shihao@shihao-T490V2:~/Code/PAN/FlightSoftware$ python -m ptest runsim -c ptest/configs/hitl.json -t EmptyCase
 _______     _       ____  _____                                
|_   __ \   / \     |_   \|_   _|                            
  | |__) | / _ \      |   \ | |                               
  |  ___/ / ___ \     | |\ \| |                              
 _| |_  _/ /   \ \_  _| |_\   |_                             
|_____||____| |____||_____|\____|                              
                                                                
Pathfinder for Autonomous Navigation                            
Space Systems Design Studio, Cornell University       
Console Software | Version 1.0

Opened connection to FlightController.
Running mission testcase EmptyCase.
[TESTCASE] Starting testcase.
[TESTCASE] Suppressing faults.
Turning off fault_handler
Turning off piksi_fh
Turning off qfh
Supressing gomspace.low_batt
Supressing gomspace.get_hk.base
Supressing prop.overpressured
Supressing prop.tank2_temp_high
Supressing prop.tank1_temp_high
Supressing adcs_monitor.functional_fault
Supressing adcs_monitor.wheel1_fault
Supressing adcs_monitor.wheel2_fault
Supressing adcs_monitor.wheel3_fault
Supressing adcs_monitor.wheel_pot_fault
Supressing attitude_estimator.fault
Supressing piksi_fh.dead
[TESTCASE] Auto-dbtelem INACTIVE
[TESTCASE] Scrape-uplink ACTIVE
[TESTCASE] Boot utility waiting to reach initial state.
Beginning console.
Type "help" for a list of commands.
NOTE: You are currently connected to the FlightController.
> [TESTCASE] Finished testcase.

> rs pan.bootcount
2                                               (Completed in 5172 us)
> Exiting command line.
Stopping binary monitor thread...
Stopping uplink console...
Terminating 0 radio connection(s)...
Terminating 1 device connection(s)...
 - Terminating console connection to and saving logging/telemetry data for FlightController.
 - Finished terminating for FlightController.
(venv) shihao@shihao-T490V2:~/Code/PAN/FlightSoftware$

**Comment by shihaocao** [comment]
See that in the above log, an Empty Case was run for the first time where bootcount was 1, then it was reboot, and then the next time the Empty Case shows bootcount as == 2.

**Comment by knk38** [comment]
Okay, so looks like we can close this issue given we see bootcount change?
